export const LIGHT_THEME = {
  MAIN_BG: '#FFFEFF',
  POST_COLOR: '#f8f4f4',

  MAIN_COLOR: '#4C83FF',

  //ELEMENTS
  INPUT_BG: '#FFFFFF',
  BUTTON_COLOR: '#4C83FF',
  LIKE_COLOR: '#4c4b4b',

  //FONT COLORS
  FONT: '#212121',
  FONT_LABEL: '#9b9b9b',
}
